services: 
  app:
    build: .
    ports:
      - 3399:3399
    depends_on:
      - db
    networks:
      - deploy_count_network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: senha123rte
      MYSQL_DATABASE: deploy_count
    ports:
      - 3306:3306
    networks:
      - deploy_count_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  deploy_count_network:

volumes:
  mysql_data: